# # It contains all the configs required in the project

# artifacts:
#   ARTIFACTS_DIR: artifacts
#   TRAINED_MODEL_DIR: model
#   BASE_MODEL_DIR: base_model
#   BASE_MODEL_NAME: base_model.h5
#   UPDATED_BASE_MODEL_NAME: updated_base_model.h5
#   CHECKPOINT_DIR: checkpoints
#   BASE_LOG_DIR: base_model_dir
#   TENSORBOARD_ROOT_LOG_DIR: tensorboard_log_dir
#   CALLBACKS_DIR: callbacks

# source_download_dirs:
#   - path_to_data_1
#   - path_to_data_1

# local_data_dirs:
#   - path_to_local_data_1
#   - path_to_local_data_2

# It contains all the configs required in the project
 
artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_OUT_TRAIN: train.pkl
  FEATURIZED_OUT_TEST: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl
 
 
metrics:
  SCORES: scores.json
 
plots:
  PRC: prc.json
  ROC: roc.json
 
source_data:
  data_dir: data
  data_file: data.xml